### ISSUE TITLE
Not able to load model in android

### ISSUE THREAD

**Issue by dymerseprojects** [dahburj/Barracuda-PoseNet#8] opened 2020-06-13 07:38 UTC
Mines a Lenovo android phone i was just trying to test the application it seems the applications builds to the device and on necessary permission it renders the camera, but no result in the android logcat it shows directory not found while trying to load the model. is there any special way to load the model as streaming assets should be loaded automatically with the apk, on checking i found out there is no streaming assets Dir thats being created in the device

**Comment by konsnos** [comment] 2020-06-17 07:11
I have the same issue. The error is 
```
2020/06/17 10:03:10.049 22756 22776 Error Unity DirectoryNotFoundException: Could not find a part of the path "/jar:file:/data/app/com.DefaultCompany.NewPoseNet-qPwAQn2fgARyxxruPDXssA==/base.apk!/assets/model-mobilenet_v1_050.bytes".
at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0017d] in <c79628fadf574d3a8feae0871fad28ef>:0 
at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean isAsync, System.Boolean anonymous) [0x00000] in <c79628fadf574d3a8feae0871fad28ef>:0 
at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access) [0x00000] in <c79628fadf574d3a8feae0871fad28ef>:0 
at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess)
at Barracuda.ModelLoader.Open (Sy
```

and later on I get `GPU readback error` from *2020/06/17 10:03:41.104 22756 22776 Info Unity WebCameraExample:Update() (at {...}\Barracuda-PoseNet\Assets\POSE-NET\Scripts\WebCameraExample.cs:103)*

Unity version is 2019.4.0f1 and this apk was built with the NDK provided by Unity Hub.

**Comment by konsnos** [comment] 2020-06-17 08:26
The issue is resolved by loading the model from Streaming Assets with [Better Streaming Assets](https://assetstore.unity.com/packages/tools/input-management/better-streaming-assets-103788).

Add an Awake method for the initialisation
```
void Awake()
{
    BetterStreamingAssets.Initialize();
}
```

Later in the method `WebCameraExamples.PoseUpdateNotTex()` change the loading script to this
```
Model _model;
if (Application.platform == RuntimePlatform.Android)
{
    byte[] modelBytes = BetterStreamingAssets.ReadAllBytes(modelName + ".bytes");
    _model = ModelLoader.Load(modelBytes);
}
else
{
    _model = ModelLoader.LoadFromStreamingAssets(modelName + ".bytes");
}
```

**Closed as completed** 2021-08-03 06:16 UTC
